name: bst_override_repro
min-version: 2.6
element-path: elements

options:
  some_option:
    type: enum
    description: Generic option for repro
    values:
      - x
      - y
    default: x
    variable: some_option

(@):
  - subproject.bst:include/extra.yml

junctions:
  internal:
    - self_junction.bst
    - subproject.bst
